# Site Settings

# paginate:            5

# Build settings
markdown:            kramdown # use <TAG markdown="1"> to render markdown within HTML tags!
mathjax:             true
highlighter:         rouge
permalink:           /blog/:title.html #none
plugins:
  - jekyll-paginate
  # - jekyll-gist # run: gem install jekyll-gist
  # - jekyll-sitemap
  # - jekyll-feed

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#   path:	     rss-feed.xml

# rouge-specific configuration; enable line numbers in code by default
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
